from datetime import date, timedelta
from elibrary.models import Librarian, Member, ExtensionPrice, Book, Extension, Rental
from elibrary import db, create_app, bcrypt

app = create_app()

with app.app_context():
    db.drop_all()
    db.create_all()

    pass1 = bcrypt.generate_password_hash('mikamika').decode('utf-8')
    pass2 = bcrypt.generate_password_hash('perapera').decode('utf-8')
    pass3 = bcrypt.generate_password_hash('djokadjoka').decode('utf-8')
    admin2 = Librarian(first_name='Pera', last_name='Perić', username='pera.peric', password=pass2, phone='0651128767', address='Peroslava Perića 5, Bileća', is_admin=True, date_registered=date(1991, 7, 23))
    admin1 = Librarian(first_name='Mika', last_name='Mikić', username='mika.mikic', password=pass1, email='mikam@gmail.com', phone='+387664408404', address='Milivoja Mikića 3, Nevesinje', date_registered=date(2013, 9, 3))
    admin3 = Librarian(first_name='Đoka', last_name='Đokić', username='djoka.djokic', password=pass3, email='djoka.kralj@outlook.com', phone='0591128767', address='Đorđija Đokića 21, Istočno Sarajevo', date_registered=date(2002, 11, 14), is_active=False)
    db.session.add(admin1)
    db.session.add(admin2)
    db.session.add(admin3)

    member1 = Member(id=3, first_name='Steva', last_name='Zikic', father_name='Jovan', profession='dip. Ekonomista', phone='+38763898554', email='steva.zikic22@live.com', address='Zike Zikica 21, Pirot', date_registered=date(2016, 2, 18), total_books_rented=15, date_expiration=date(2021, 2, 24), number_of_rented_books=1)
    member2 = Member(id=18, first_name='Vida', last_name='Stevic', father_name='Petar', profession='dip. Pravnik', phone='0594545332', address='Stevice Stevovica 54, Beograd', date_registered=date(2011, 5, 12), total_books_rented=1, date_expiration=date(2012, 5, 12), number_of_rented_books=1)
    member3 = Member(id=24, first_name='Rade', last_name='Vidic', father_name='Luka', profession='dip. inž. Mašinstva', phone='0654433565', email='radev@gmail.com', address='Vidvdanska 8, Valjevo', date_registered=date(1998, 3, 18), total_books_rented=16754, date_expiration=date(2020, 5, 20), number_of_rented_books=1)
    member4 = Member(id=42, first_name='Ana', last_name='Radovic', father_name='Matej', profession='master Biologije', phone='066232445', address='Bulevar Radoslava Radenkovića Raše 133, Kosovska Mitrovica', date_registered=date(2008, 10, 27), total_books_rented=375, date_expiration=date(2019, 10, 7), number_of_rented_books=0)
    member5 = Member(id=76, first_name='Žika', last_name='Anic', father_name='Andrej', profession='dr Primenjene Matematike', phone='+387593037566', email='zikans@gmail.com', address='Atinska 58, Novi Sad', date_registered=date(2019, 7, 23), total_books_rented=2742, date_expiration=date(2020, 7, 23), number_of_rented_books=2)
    member6 = Member(id=103, first_name='Petar', last_name='Milov', father_name='Nikola', profession='dipl. Fizičar', phone='+387691215464', address='Fruškogorska 12, Sremska Kamenica', date_registered=date(2012, 8, 14), total_books_rented=12, date_expiration=date(2020, 12, 30), number_of_rented_books=4)
    member7 = Member(id=104, first_name='Vera', last_name='Milov', father_name='Nikola', profession='dipl. Hemičar', phone='+387695545465', address='Fruškogorska 12, Sremska Kamenica', date_registered=date(2012, 8, 14), total_books_rented=12, date_expiration=date(2020, 12, 30), number_of_rented_books=0)        
    db.session.add(member1)
    db.session.add(member2)
    db.session.add(member3)
    db.session.add(member4)
    db.session.add(member5)
    db.session.add(member6)
    db.session.add(member7)        
    
    book1 = Book(id=1, signature='21.125-123-55', inv_number='12', title='Derviš i smrt', author='Meša Selimović', is_rented=True, has_error=False)
    book2 = Book(id=2, signature='21.125-123-55', inv_number='45', title='Prokleta avlija', author='Ivo Andrić', is_rented=True, has_error=False)
    book3 = Book(id=3, signature='21.125-123-76', inv_number='76', title='Znamenje anđela', author='Dejan Stojiljković', is_rented=True, has_error=False)
    book4 = Book(id=4, signature='23.543-321-77', inv_number='104', title='Olujni bedem', author='Dejan Stojiljković', is_rented=False, has_error=False)
    book5 = Book(id=5, signature='64.243-987-02', inv_number='176', title='Stefan Prvovenčani', author='Luka Mičeta', is_rented=True, has_error=True)
    book6 = Book(id=6, signature='64.243-879-27', inv_number='176', title='Stefan Nemanja', author='Luka Mičeta', is_rented=False, has_error=True)
    book7 = Book(id=7, signature='18.723-908-41', inv_number='608', title='Savršeno sećanje na smrt', author='Radoslav Petković', is_rented=False, has_error=False)
    book8 = Book(id=8, signature='15.127-436-13', inv_number='732', title='Simeonov pečat', author='Vanja Bulić', is_rented=True, has_error=False)
    book9 = Book(id=9, signature='96.598-702-48', inv_number='828', title='Dnevnik jednog čarobnjaka', author='Paolo Koeljo', is_rented=False, has_error=False)
    book10 = Book(id=10, signature='15.127-809-43', inv_number='1004', title='Kada govori mrtav kralj', author='Ivan Miladinović', is_rented=True, has_error=False)
    book11 = Book(id=11, signature='74.183-704-33', inv_number='3298', title='Nulta krvna grupa', author='Slavko Nikić', is_rented=True, has_error=False)
    book12 = Book(id=12, signature='96.598-702-48', inv_number='3305', title='Peta Gora', author='Paolo Koeljo', is_rented=False, has_error=False)
    book13 = Book(id=13, signature='38.563-123-78', inv_number='6987', title='Komitet 300', author='Džon Kolman', is_rented=True, has_error=False)
    book14 = Book(id=14, signature='96.598-702-48', inv_number='10238', title='Peta Gora', author='Paolo Koeljo', is_rented=True, has_error=False)
    db.session.add(book1)
    db.session.add(book2)
    db.session.add(book3)
    db.session.add(book4)
    db.session.add(book5)
    db.session.add(book6)
    db.session.add(book7)
    db.session.add(book8)
    db.session.add(book9)
    db.session.add(book10)
    db.session.add(book11)
    db.session.add(book12)
    db.session.add(book13)
    db.session.add(book14)

    price1 = ExtensionPrice(id=1, price_value=0.0, currency='KM', note="Besplatno")
    price2 = ExtensionPrice(id=2, price_value=7.99, currency='KM', note="Letnji popust", is_enabled=False)
    price3 = ExtensionPrice(id=3, price_value=10.0, currency='KM')
    price4 = ExtensionPrice(id=4, price_value=14.00, currency='KM', note="Novogodišnja akcija - dve članarine", is_enabled=False)
    db.session.add(price1)
    db.session.add(price2)
    db.session.add(price3)
    db.session.add(price4)
  
    extension1 = Extension(note='', price=10.00, date_performed=date(1999, 3, 23), date_extended=date(1999, 3, 23), price_id=3, member_id=24, price_details=price3, member=member3)
    extension2 = Extension(note='Učenik osnovne škole ne plaća članarinu', price=0.00, date_performed=date(2010, 1, 3), date_extended=date(2011, 1, 3), price_id=1, member_id=42, price_details=price1, member=member4)
    extension3 = Extension(note='', price=10.00, date_performed=date(2011, 5, 12), date_extended=date(2012, 5, 12), price_id=3, member_id=18, price_details=price3, member=member2)
    extension4 = Extension(note='Cena letnjeg popusta', price=7.99, date_performed=date(2012, 8, 14), date_extended=date(2013, 8, 14), price_id=2, member_id=103, price_details=price2, member=member6)
    extension5 = Extension(note='Cena letnjeg popusta', price=7.99, date_performed=date(2012, 8, 14), date_extended=date(2013, 8, 14), price_id=2, member_id=104, price_details=price2, member=member7)
    extension6 = Extension(note='Prva uplata', price=10.00, date_performed=date(2016, 2, 18), date_extended=date(2017, 2, 18), price_id=3, member_id=3, price_details=price3, member=member1)
    extension7 = Extension(note='', price=10.00, date_performed=date(2017, 9, 28), date_extended=date(2018, 9, 28), price_id=3, member_id=3, price_details=price3, member=member1)
    extension8 = Extension(note='Redovno produženje članarine', price=10.00, date_performed=date(2018, 9, 21), date_extended=date(2019, 9, 28), price_id=3, member_id=3, price_details=price3, member=member1)
    extension9 = Extension(note='Učenik osnovne škole ne plaća članarinu', price=0.00, date_performed=date(2018, 10, 7), date_extended=date(2019, 10, 7), price_id=1, member_id=42, price_details=price1, member=member4)
    extension10 = Extension(note='Produženje, cena redovna', price=10.00, date_performed=date(2019, 5, 25), date_extended=date(2020, 5, 25), price_id=3, member_id=24, price_details=price3, member=member3)
    extension11 = Extension(note='Cena letnjeg popusta', price=7.99, date_performed=date(2019, 7, 23), date_extended=date(2020, 7, 23), price_id=2, member_id=76, price_details=price2, member=member5)
    extension12 = Extension(note='Član 104 ne plaća jer ovaj član plaća iznos akcije', price=14.00, date_performed=date(2019, 12, 30), date_extended=date(2020, 12, 30), price_id=4, member_id=103, price_details=price4, member=member6)
    extension13 = Extension(note='Ovaj član ne plaća članarinu, jer član 103 plaća iznos akcije', price=0.00, date_performed=date(2019, 12, 30), date_extended=date(2020, 12, 30), price_id=1, member_id=104, price_details=price1, member=member7)
    extension14 = Extension(note='', price=10.00, date_performed=date(2020, 2, 24), date_extended=date(2021, 2, 24), price_id=3, member_id=3, price_details=price3, member=member1)
    db.session.add(extension1)
    db.session.add(extension2)
    db.session.add(extension3)
    db.session.add(extension4)
    db.session.add(extension5)
    db.session.add(extension6)
    db.session.add(extension7)
    db.session.add(extension8)
    db.session.add(extension9)
    db.session.add(extension10)
    db.session.add(extension11)
    db.session.add(extension12)
    db.session.add(extension13)
    db.session.add(extension14)

    rental1 = Rental(date_performed=date(1999, 8, 8), date_deadline=date(1999, 8, 22), date_termination=date(1999, 8, 31), is_terminated=True, book_id=3, member_id=24, book=book3, member=member3)    
    rental2 = Rental(date_performed=date(2010, 2, 16), date_deadline=date(2010, 3, 2), date_termination=date(2010, 3, 12), is_terminated=True, book_id=7, member_id=42, book=book7, member=member4)
    rental3 = Rental(date_performed=date(2011, 5, 15), date_deadline=date(2011, 5, 29), date_termination=date(2011, 6, 29), is_terminated=True, book_id=6, member_id=18, book=book6, member=member2)
    rental4 = Rental(date_performed=date(2011, 9, 28), date_deadline=date(2011, 10, 12), date_termination=date(2011, 12, 28), is_terminated=True, book_id=10, member_id=18, book=book10, member=member2)
    rental5 = Rental(date_performed=date(2012, 8, 14), date_deadline=date(2012, 8, 28), date_termination=date(2012, 8, 25), is_terminated=True, book_id=2, member_id=103, book=book2, member=member6)
    rental7 = Rental(date_performed=date(2016, 3, 19), date_deadline=date(2016, 4, 2), date_termination=date(2016, 4, 2), is_terminated=True, book_id=14, member_id=3, book=book14, member=member1)
    rental8 = Rental(date_performed=date(2016, 6, 30), date_deadline=date(2016, 7, 14), date_termination=date(2016, 7, 6), is_terminated=True, book_id=8, member_id=3, book=book8, member=member1)
    rental9 = Rental(date_performed=date(2018, 10, 7), date_deadline=date(2018, 10, 21), date_termination=date(2018, 10, 20), is_terminated=True, book_id=12, member_id=42, book=book12, member=member4)
    rental10 = Rental(date_performed=date(2018, 12, 11), date_deadline=date(2018, 12, 25), date_termination=date(2019, 1, 12), is_terminated=True, book_id=2, member_id=3, book=book2, member=member1)    
    rental11 = Rental(date_performed=date(2019, 4, 16), date_deadline=date(2019, 4, 30), date_termination=date(2019, 4, 29), is_terminated=True, book_id=10, member_id=42, book=book10, member=member4)
    rental12 = Rental(date_performed=date(2019, 10, 2), date_deadline=date(2019, 10, 16), date_termination=date(2019, 10, 15), is_terminated=True, book_id=7, member_id=76, book=book7, member=member5)                                                                                                                    
    rental13 = Rental(date_performed=date(2019, 12, 16), date_deadline=date(2019, 12, 30), date_termination=date(2020, 2, 10), is_terminated=True, book_id=10, member_id=24, book=book10, member=member3)    
    rental14 = Rental(date_performed=date(2019, 12, 30), date_deadline=date(2020, 1, 13), date_termination=date(2020, 1, 9), is_terminated=True, book_id=1, member_id=103, book=book11, member=member6)
    rental15 = Rental(date_performed=date(2020, 1, 13), date_deadline=date(2020, 1, 27), date_termination=date(2020, 1, 27), is_terminated=True, book_id=4, member_id=103, book=book4, member=member6)
    rental16 = Rental(date_performed=date(2020, 1, 20), date_deadline=date(2020, 2, 3), date_termination=date(2020, 1, 31), is_terminated=True, book_id=13, member_id=103, book=book13, member=member6)    
    rental6 = Rental(date_performed=date(2012, 3, 15), date_deadline=date(2012, 3, 29), date_termination=None, is_terminated=False, book_id=3, member_id=18, book=book3, member=member2)
    rental17 = Rental(date_performed=date(2020, 2, 1), date_deadline=date(2020, 2, 15), date_termination=None, is_terminated=False, book_id=8, member_id=103, book=book8, member=member6)
    rental18 = Rental(date_performed=date(2020, 3, 18), date_deadline=date(2020, 4, 1), date_termination=None, is_terminated=False, book_id=10, member_id=76, book=book10, member=member5)    
    rental19 = Rental(date_performed=date.today()-timedelta(15), date_deadline=date.today()-timedelta(1), date_termination=None, is_terminated=False, book_id=11, member_id=3, book=book11, member=member1)
    rental20 = Rental(date_performed=date.today()-timedelta(14), date_deadline=date.today(), date_termination=None, is_terminated=False, book_id=5, member_id=24, book=book5, member=member3)
    rental21 = Rental(date_performed=date.today()-timedelta(10), date_deadline=date.today()+timedelta(4), date_termination=None, is_terminated=False, book_id=1, member_id=103, book=book1, member=member6)
    rental22 = Rental(date_performed=date.today()-timedelta(5), date_deadline=date.today()+timedelta(9), date_termination=None, is_terminated=False, book_id=12, member_id=103, book=book12, member=member6)
    rental23 = Rental(date_performed=date.today()-timedelta(1), date_deadline=date.today()+timedelta(13), date_termination=None, is_terminated=False, book_id=14, member_id=76, book=book14, member=member5)
    rental24 = Rental(date_performed=date.today(), date_deadline=date.today()+timedelta(14), date_termination=None, is_terminated=False, book_id=2, member_id=103, book=book2, member=member6)
    db.session.add(rental1)
    db.session.add(rental2)
    db.session.add(rental3)
    db.session.add(rental4)
    db.session.add(rental5)
    db.session.add(rental6)
    db.session.add(rental7)
    db.session.add(rental8)
    db.session.add(rental9)
    db.session.add(rental10)
    db.session.add(rental11)
    db.session.add(rental12)
    db.session.add(rental13)
    db.session.add(rental14)
    db.session.add(rental15)
    db.session.add(rental16)
    db.session.add(rental17)
    db.session.add(rental18)
    db.session.add(rental19)
    db.session.add(rental20)
    db.session.add(rental21)
    db.session.add(rental22)
    db.session.add(rental23)
    db.session.add(rental24)

    db.session.commit()
