from datetime import date
from elibrary.models import Librarian, Member, ExtensionPrice, Book
from elibrary import db, create_app, bcrypt

app = create_app()

with app.app_context():
    db.drop_all()
    db.create_all()

    pass1 = bcrypt.generate_password_hash('mikamika').decode('utf-8')
    pass2 = bcrypt.generate_password_hash('perapera').decode('utf-8')
    pass3 = bcrypt.generate_password_hash('djokadjoka').decode('utf-8')
    admin2 = Librarian(first_name='Pera', last_name='Peric', username='pera.peric', password=pass2, phone='0651128767', address='Peroslava Perica 5, Bileća', is_admin=True, date_registered=date(1991, 7, 23))
    admin1 = Librarian(first_name='Mika', last_name='Mikic', username='mika.mikic', password=pass1, email='mikam@gmail.com', phone='+387664408404', address='Milivoja Mikica 3, Nevesinje', date_registered=date(2013, 9, 3))
    admin3 = Librarian(first_name='Djoka', last_name='Djokic', username='djoka.djokic', password=pass3, email='djoka.kralj@outlook.com', phone='0591128767', address='Djoleta Djokica 21, Istočno Sarajevo', date_registered=date(2002, 11, 14), is_operational=False)
    db.session.add(admin1)
    db.session.add(admin2)
    db.session.add(admin3)

    member1 = Member(id=27, first_name='Steva', last_name='Zikic', father_name='Jovan', profession='dip. Ekonomista', phone='+38763898554', email='steva.zikic22@live.com', address='Zike Zikica 21, Pirot', date_registered=date(2016, 2, 18), total_books_rented=15, date_expiration=date(2018, 3, 2))
    member2 = Member(id=32, first_name='Vida', last_name='Stevic', father_name='Petar', profession='dip. Pravnik', phone='0594545332', address='Stevice Stevovica 54, Beograd', date_registered=date(2011, 5, 12), total_books_rented=1, date_expiration=date(2020, 4, 25))
    member3 = Member(id=805, first_name='Rade', last_name='Vidic', father_name='Luka', profession='dip. inž. Mašinstva', phone='0654433565', email='radev@gmail.com', address='Vidvdanska 8, Valjevo', date_registered=date(1998, 3, 18), total_books_rented=16754, date_expiration=date(2021, 3, 2))
    member4 = Member(id=2, first_name='Ana', last_name='Radovic', father_name='Matej', profession='master Biologije', phone='066232445', address='Bulevar Radoslava Radenkovića Raše 133, Kosovska Mitrovica', date_registered=date(2008, 10, 27), total_books_rented=375, date_expiration=date(2020, 5, 4))
    member5 = Member(id=1003, first_name='Žika', last_name='Anic', father_name='Andrej', profession='dr Primenjene Matematike', phone='+387593037566', email='zikans@gmail.com', address='Atinska 58, Novi Sad', date_registered=date(2019, 7, 23), total_books_rented=2742, date_expiration=date(2020, 10, 14))
    member6 = Member(id=658, first_name='Petar', last_name='Milov', father_name='Nikola', profession='dipl. Fizičar', phone='+387691215464', address='Fruškogorska 12, Sremska Kamenica', date_registered=date(2012, 8, 14), total_books_rented=12)
    db.session.add(member1)
    db.session.add(member2)
    db.session.add(member3)
    db.session.add(member4)
    db.session.add(member5)
    db.session.add(member6)
        
    price1 = ExtensionPrice(price_value=0.0, currency='KM', note="Free of charge")
    price2 = ExtensionPrice(price_value=10.0, currency='KM')
    price3 = ExtensionPrice(price_value=7.99, currency='KM', note="New Year discount", is_enabled=False)
    db.session.add(price1)
    db.session.add(price2)
    db.session.add(price3)
    
    book1 = Book(signature='21.125-123-55', inv_number='12', title='Derviš i smrt', author='Meša Selimović')
    book2 = Book(signature='21.125-123-55', inv_number='45', title='Prokleta avlija', author='Ivo Andrić')
    book3 = Book(signature='21.125-123-76', inv_number='76', title='Blago cara Radovana', author='Jovan Dučić')
    book4 = Book(signature='23.543-321-77', inv_number='104', title='Olujni bedem', author='Dejan Stojiljković')
    book5 = Book(signature='64.243-987-02', inv_number='176', title='Komitet 300', author='Džon Kolman')
    book6 = Book(signature='38.563-123-78', inv_number='298', title='Stefan Nemanja', author='Luka Mičeta')
    book7 = Book(signature='64.243-879-27', inv_number='608', title='Savršeno sećanje na smrt', author='Radoslav Petković')
    book8 = Book(signature='15.127-436-13', inv_number='1012', title='Simeonov pečat', author='Vanja Bulić')
    book9 = Book(signature='96.598-702-48', inv_number='2309', title='Dnevnik jednog čarobnjaka', author='Paolo Koeljo')
    book10 = Book(signature='15.127-809-43', inv_number='9055', title='Kada govori mrtav kralj', author='Ivan Miladinović')
    book11 = Book(signature='74.183-704-33', inv_number='13088', title='Nulta krvna grupa', author='Slavko Nikić')
    db.session.add(book1)
    db.session.add(book2)
    db.session.add(book3)
    db.session.add(book4)
    db.session.add(book5)
    db.session.add(book6)
    db.session.add(book7)
    db.session.add(book8)
    db.session.add(book9)
    db.session.add(book10)
    db.session.add(book11)    

    db.session.commit()
