BACKWARD_INPUT_LIMIT = 30    # kada se kreira nalog za bibliotekara i korisnika datum kreiranja se moze postaviti za ovaj broj dana u nazad
RENTAL_DATE_LIMIT = 7
EXPIRATION_EXTENSION_LIMIT = 30 # kada se produzava clanstvo, moze se produziti nakon isteka i ovaj broj dana pre isteka
BOOK_RENT_PERIOD = 14
PAGINATION = 5
MAXIMUM_NUMBER = 50000
MAX_RENTED_BOOKS = 5
DATE_FORMAT = '%d.%m.%Y.'
MINIMUM_DATE = '01.01.1980.'    # !!!!!!!! Update if DATE_FORMAT changed
